### ISSUE TITLE
[Bug]: Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### ISSUE THREAD

**Issue by devhoussam1998** [rupadana/filament-slider#7]
### What happened?

Problem 1
    - Root composer.json requires rupadana/filament-slider * -> satisfiable by rupadana/filament-slider[1.0.0].
    - rupadana/filament-slider 1.0.0 requires illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.20] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require rupadana/filament-slider:*" to figure out if any version is installable, or "composer require rupadana/filament-slider:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### How to reproduce the bug

`composer require rupadana/filament-slider`

### Package Version

1.0.0

### PHP Version

^8.2

### Laravel Version

^11.0

### Which operating systems does with happen with?

macOS

**Comment by tim24** [comment]
Same

**Comment by rupadana** [comment]
please update to version 1.0.1 #8

**Comment by rupadana** [comment]
what data type of your column?

**Comment by tim24** [comment]
Tried with integer and also with json column that is cast but still always adds the ".00" 

`protected function casts(): array
    {
        return [
            'monthly_limit' => 'integer',
            'total_limit' => 'integer',
            'target' => 'array',
            'target.total_min' => 'integer',
            'target.total_max' => 'integer'
        ];
    }`
